Make Silos optional
mindbender-studio/launcher pull request #46
Opened 2020-04-03 14:41 UTC by iLLiCiTiT

PR related to core's PR https://github.com/getavalon/core/pull/535.
- this is version of launcher with ability to work with or without silo
- most of changes happened a long time ago, so feel free to comment, modify or even create better PR, this works but I would say it is not clean code

2020-04-04 08:50 UTC, mottosso commented
Thanks. I don't mind that it's dirty. As far as I'm concerned, Launcher is on life-support until Allzpark replaces it. @davidlatwe Are you using Launcher? If you're happy with the changes, I'm happy.

2020-04-06 04:25 UTC, davidlatwe reviewed
Yeah, still using *life-support* here. 🙋‍♂ 
Just one question about this change. 👇

2020-04-06 04:25 UTC, davidlatwe commented on launcher/control.py
> +        frame = project
Why removing `frame = self.current_frame()`, `frame["config"] = project["config"]` and use entire project document as frame ?

Is this necessary ? If not, I would like to keep it :D

2020-04-17 17:58 UTC, davidlatwe requested changes
Okay, sorry for late review but I just re-visited this and have a few tests.
Once these fixed, we are good to go !

2020-04-17 17:58 UTC, davidlatwe commented on launcher/control.py
> +            }[frame["type"]]
It look like `frame` in first launch did not have key `"type"`, so the above if-statement should change into
```python
if frame and frame.get("type"):
    ...
````

2020-04-17 17:58 UTC, davidlatwe commented on launcher/control.py
> -        self._frames[:] = [frame]
We need these two lines or `KeyError: environment` will raised later in `on_project_changed` (at line 332).

2020-04-17 18:31 UTC, davidlatwe approved these changes

2020-04-17 18:33 UTC, davidlatwe commented
Thanks @iLLiCiTiT , although this PR is backward compatible (quick tested), but let's wait for getavalon/core#535 to be merged for clarity.

2024-08-12 08:48 UTC, closed without merging